### POST CLIENT
POST http://localhost:8080/api/clients/
Content-Type: application/json

{
    "name": "Clínica Veterinaria Mitre",
    "email": "mitre@vet.com",
    "address": "Bartolomé Mitre 678",
    "phone": "1198765432",
    "veterinarians": []
}


### GET CLIENTS

GET http://localhost:8080/api/clients/


### GET CLIENT BY ID
GET http://localhost:8080/api/clients/68c2ac79093877decae19d2a


### PUT CLIENT
PUT http://localhost:8080/api/clients/6887e6099456012b51943dc2
Content-Type: application/json

{
  "name": "New Client Name"
}

### DELETE CLIENT

DELETE http://localhost:8080/api/clients/68c2ac79093877decae19d2a
