### POST REPORT
POST http://localhost:8080/api/reports/
Content-Type: application/json

{
  "protocolNumber": "00004",
  "veterinarian": "Dra. Gómez",
  "client": "68c2ac80093877decae19d2d",
  "studyType": "hp",
  "sampleInfo": "Muestra de tejido muscular de la pata trasera.",
  "macroDescription": "Tejido firme, color rosado claro, sin signos de necrosis.",
  "microDescription": "Células musculares normales, infiltrado inflamatorio leve.",
  "comments": "Paciente se recupera bien de su cirugía reciente.",
  "result": "Sin hallazgos patológicos graves.",
  "patient": {
    "owner": "María López",
    "name": "Milo",
    "species": "Gato",
    "breed": "Siamés",
    "age": "4 años",
    "sex": "hembra",
    "color": "Gris claro",
    "neutered": false
  }
}


### GET REPORTS

GET http://localhost:8080/api/reports/


### GET REPORT BY ID

GET http://localhost:8080/api/reports/689133bfac4c7b1c6579c7d4


### GET REPORT BY NUMBER

GET http://localhost:8080/api/reports/number/00002


### PUT REPORT

PUT http://localhost:8080/api/reports/689133bfac4c7b1c6579c7d4
Content-Type: application/json

{
  "client": "68b60b84219ddcbd20d0eda2",
  "protocolNumber": "00001",
  "patient": {
    "sex": "hembra"
  }
}

### DELETE REPORT

DELETE http://localhost:8080/api/reports/68b7601933dc1c7c3e78759e


### GET REPORT IN PDF

GET http://localhost:8080/api/reports/pdf/689133bfac4c7b1c6579c7d4
