### POST REPORT
POST http://localhost:8080/api/reports/
Content-Type: application/json

{
  "protocolNumber": "00002",
  "patient": {
    "sex": "hembra"
  },
  "client": "68b60b84219ddcbd20d0eda2",
  "studyType": "hp"
}


### GET REPORTS

GET http://localhost:8080/api/reports/


### GET REPORT BY ID

GET http://localhost:8080/api/reports/689133bfac4c7b1c6579c7d4


### GET REPORT BY NUMBER

GET http://localhost:8080/api/reports/number/00002


### PUT REPORT

PUT http://localhost:8080/api/reports/689133bfac4c7b1c6579c7d4
Content-Type: application/json

{
  "client": "68b60b84219ddcbd20d0eda2",
  "protocolNumber": "00001",
  "patient": {
    "sex": "hembra"
  }
}

### DELETE REPORT

DELETE http://localhost:8080/api/reports/68b7601933dc1c7c3e78759e


### GET REPORT IN PDF

GET http://localhost:8080/api/reports/pdf/689133bfac4c7b1c6579c7d4
